name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4 # 升级到 v4，消除你的黄字警告
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Smart Build APK
        run: |
          # 1. 自动全盘寻找 gradlew 文件并赋予执行权限
          find . -name "gradlew" -exec chmod +x {} \;
          # 2. 自动在 gradlew 所在的目录执行 Debug 打包 (避开正式版签名报错)
          find . -name "gradlew" -execdir ./gradlew assembleDebug \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PiliPlusFPS-Module
          path: "**/app/build/outputs/apk/**/*.apk" # 智能全盘抓取生成的 APK
