name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Smart Build APK
        run: |
          find . -name "gradlew" -exec chmod +x {} \;
          find . -name "gradlew" -execdir ./gradlew assembleDebug \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PiliPlusFPS-Module
          path: "**/*.apk" # 终极修改：无视文件夹层级，全盘抓取所有生成的 apk
